/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicButtonUI;
/**
 *
 * @author trant
 */
public class mainView extends javax.swing.JFrame {

    private JPanel childPanel;

    /**
     * Creates new form mainView
     */
    public mainView() {

      initComponents();
        setLocationRelativeTo(null);
        setpanel(new SanPham());
        color();
        JButton[] btn1= {btnBanHang,btnExit,btnHoaDon,btnKhachHang,btnNhanVien,btnThongKe,btnVoucher};
        JButton[] btn2= {btnSanPham};
        for (JButton btn22 : btn2) {
            btn22.setBackground(new Color(103,204,255));
        }
        for (JButton btn11 : btn1) {
            btn11.setBackground(new Color(204,255,255));
        }
    }

    
    private void setpanel(JPanel panel) {
        childPanel = panel;
        pnmain.removeAll();
        pnmain.add(childPanel);
        pnmain.validate();
    }
    
    
    private void color(){
        JButton[] btns = {btnBanHang,btnExit,btnHoaDon,btnKhachHang,btnNhanVien,btnSanPham,btnThongKe,btnVoucher};
        for (JButton btn : btns) {
            btn.setBackground(new Color(204,255,255));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnmain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnSanPham = new javax.swing.JButton();
        btnBanHang = new javax.swing.JButton();
        btnVoucher = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(null);

        pnmain.setBackground(new java.awt.Color(255, 255, 255));
        pnmain.setMaximumSize(new java.awt.Dimension(940, 580));
        pnmain.setLayout(new java.awt.BorderLayout());
        jPanel2.add(pnmain);
        pnmain.setBounds(150, 50, 940, 580);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/header1.png"))); // NOI18N
        jLabel1.setText(" ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(290, -10, 500, 80);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(790, 0, 290, 70);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(140, 0, 262, 82);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);
        jPanel5.setBounds(0, 0, 250, 60);

        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel2.add(btnExit);
        btnExit.setBounds(0, 480, 140, 60);

        btnSanPham.setText("Sản Phẩm");
        btnSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSanPhamMouseClicked(evt);
            }
        });
        jPanel2.add(btnSanPham);
        btnSanPham.setBounds(0, 60, 140, 60);

        btnBanHang.setText("Bán Hàng");
        btnBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBanHangMouseClicked(evt);
            }
        });
        jPanel2.add(btnBanHang);
        btnBanHang.setBounds(0, 120, 140, 60);

        btnVoucher.setText("Khuyến Mãi");
        btnVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoucherMouseClicked(evt);
            }
        });
        btnVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoucherActionPerformed(evt);
            }
        });
        jPanel2.add(btnVoucher);
        btnVoucher.setBounds(0, 180, 140, 60);

        btnHoaDon.setText("Hóa Đơn");
        btnHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHoaDonMouseClicked(evt);
            }
        });
        jPanel2.add(btnHoaDon);
        btnHoaDon.setBounds(0, 240, 140, 60);

        btnThongKe.setText("Thống Kê");
        btnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThongKeMouseClicked(evt);
            }
        });
        jPanel2.add(btnThongKe);
        btnThongKe.setBounds(0, 300, 140, 60);

        btnKhachHang.setText("Khách Hàng");
        btnKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKhachHangMouseClicked(evt);
            }
        });
        jPanel2.add(btnKhachHang);
        btnKhachHang.setBounds(0, 360, 140, 60);

        btnNhanVien.setText("Nhân Viên");
        btnNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhanVienMouseClicked(evt);
            }
        });
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });
        jPanel2.add(btnNhanVien);
        btnNhanVien.setBounds(0, 420, 140, 60);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoucherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoucherActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanPhamMouseClicked
        // TODO add your handling code here:
        setpanel(new SanPham());
        JButton[] btn1= {btnBanHang,btnExit,btnHoaDon,btnKhachHang,btnNhanVien,btnThongKe,btnVoucher};
        JButton[] btn2= {btnSanPham};
        for (JButton btn22 : btn2) {
            btn22.setBackground(new Color(103,204,255));
        }
        for (JButton btn11 : btn1) {
            btn11.setBackground(new Color(204,255,255));
        }
    }//GEN-LAST:event_btnSanPhamMouseClicked

    private void btnBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBanHangMouseClicked
        // TODO add your handling code here:
        setpanel(new BanHang());
        JButton[] btn1= {btnSanPham,btnExit,btnHoaDon,btnKhachHang,btnNhanVien,btnThongKe,btnVoucher};
        JButton[] btn2= {btnBanHang};
        for (JButton btn22 : btn2) {
            btn22.setBackground(new Color(103,204,255));
        }
        for (JButton btn11 : btn1) {
            btn11.setBackground(new Color(204,255,255));
        }
    }//GEN-LAST:event_btnBanHangMouseClicked

    private void btnVoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoucherMouseClicked
        // TODO add your handling code here:
        setpanel(new KhuyenMai());
        JButton[] btn1= {btnBanHang,btnExit,btnHoaDon,btnKhachHang,btnNhanVien,btnThongKe,btnSanPham};
        JButton[] btn2= {btnVoucher};
        for (JButton btn22 : btn2) {
            btn22.setBackground(new Color(103,204,255));
        }
        for (JButton btn11 : btn1) {
            btn11.setBackground(new Color(204,255,255));
        }
    }//GEN-LAST:event_btnVoucherMouseClicked

    private void btnHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoaDonMouseClicked
        // TODO add your handling code here:
        setpanel(new HoaDonChiTiet());
        JButton[] btn1= {btnBanHang,btnExit,btnSanPham,btnKhachHang,btnNhanVien,btnThongKe,btnVoucher};
        JButton[] btn2= {btnHoaDon};
        for (JButton btn22 : btn2) {
            btn22.setBackground(new Color(103,204,255));
        }
        for (JButton btn11 : btn1) {
            btn11.setBackground(new Color(204,255,255));
        }
    }//GEN-LAST:event_btnHoaDonMouseClicked

    private void btnThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseClicked
        // TODO add your handling code here:
        setpanel(new ThongKe());
        JButton[] btn1= {btnBanHang,btnExit,btnHoaDon,btnKhachHang,btnNhanVien,btnSanPham,btnVoucher};
        JButton[] btn2= {btnThongKe};
        for (JButton btn22 : btn2) {
            btn22.setBackground(new Color(103,204,255));
        }
        for (JButton btn11 : btn1) {
            btn11.setBackground(new Color(204,255,255));
        }
    }//GEN-LAST:event_btnThongKeMouseClicked

    private void btnKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachHangMouseClicked
        // TODO add your handling code here:
        setpanel(new KhachHang());
        JButton[] btn1= {btnBanHang,btnExit,btnHoaDon,btnSanPham,btnNhanVien,btnThongKe,btnVoucher};
        JButton[] btn2= {btnKhachHang};
        for (JButton btn22 : btn2) {
            btn22.setBackground(new Color(103,204,255));
        }
        for (JButton btn11 : btn1) {
            btn11.setBackground(new Color(204,255,255));
        }
    }//GEN-LAST:event_btnKhachHangMouseClicked

    private void btnNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMouseClicked
        // TODO add your handling code here:
        setpanel(new NhanVien());
        JButton[] btn1= {btnBanHang,btnExit,btnHoaDon,btnKhachHang,btnSanPham,btnThongKe,btnVoucher};
        JButton[] btn2= {btnNhanVien};
        for (JButton btn22 : btn2) {
            btn22.setBackground(new Color(103,204,255));
        }
        for (JButton btn11 : btn1) {
            btn11.setBackground(new Color(204,255,255));
        }
    }//GEN-LAST:event_btnNhanVienMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        JButton[] btn1= {btnBanHang,btnSanPham,btnHoaDon,btnKhachHang,btnNhanVien,btnThongKe,btnVoucher};
        JButton[] btn2= {btnExit};
        for (JButton btn22 : btn2) {
            btn22.setBackground(new Color(103,204,255));
        }
        for (JButton btn11 : btn1) {
            btn11.setBackground(new Color(204,255,255));
        }setVisible(false);
        new DanhNhap().setVisible(true);
            
    }//GEN-LAST:event_btnExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnVoucher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel pnmain;
    // End of variables declaration//GEN-END:variables
}
